apiVersion: batch/v1
kind: Job
metadata:
  name: app-back
  namespace: ${K8S_NAMESPACE}
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: app-back
        image: ${CI_REGISTRY_IMAGE}:app_back.${OWN_TAG}
        command: ["python",  "create.py"]
        envFrom:
          - configMapRef:
              name: app-configmap
          - secretRef:
              name: app-secret
      restartPolicy: Never
