apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front
  namespace: ${K8S_NAMESPACE}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-front
  template:
    metadata:
      labels:
        app: app-front
    spec:
      containers:
      - name: app-front
        image: ${CI_REGISTRY_IMAGE}:app_front.${OWN_TAG}
        envFrom:
          - configMapRef:
              name: app-configmap
          - secretRef:
              name: app-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000