apiVersion: v1
kind: Service
metadata:
  name: sw-app-service
  labels:
    app: app-front
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: app-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: sw-app-service
  labels:
    app: app-front
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: app-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000