apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-front
  template:
    metadata:
      labels:
        app: app-front
    spec:
      containers:
      - name: app-front
        image: registry.gitlab.com/gezm0/internship_diploma:app_front
        env:
          - name: TF_VAR_db_user
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_user
          - name: TF_VAR_db_password
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_password
          - name: TF_VAR_db_name
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_name
          - name: db_host
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: db_host
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: sw-app-service
spec:
  type: LoadBalancer
  selector:
    app: app-front
  ports:
  - port: 80
    targetPort: 5000