apiVersion: batch/v1
kind: Job
metadata:
  name: db-create
  namespace: ${K8S_NAMESPACE}
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: db-create
        image: ${CI_REGISTRY_IMAGE}:db_create.${OWN_TAG}
        command: ["python",  "db_create_tables.py"]
        envFrom:
          - configMapRef:
              name: app-configmap
          - secretRef:
              name: app-secret
      restartPolicy: Never