apiVersion: batch/v1
kind: Job
metadata:
  name: drop-db
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: drop-db
        image: 422613489304.dkr.ecr.eu-west-2.amazonaws.com/diploma_registry:drop_db.v2
        command: ["python",  "db_drop_tables.py"]
        env:
          - name: TF_VAR_db_user
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_user
          - name: TF_VAR_db_password
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_password
          - name: TF_VAR_db_name
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_name
          - name: db_host
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: db_host
      restartPolicy: Never