apiVersion: batch/v1
kind: Job
metadata:
  name: db-drop
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: db-drop
        image: registry.gitlab.com/gezm0/internship_diploma:db_drop
        command: ["python",  "db_drop_tables.py"]
        env:
          - name: TF_VAR_db_user
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_user
          - name: TF_VAR_db_password
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_password
          - name: TF_VAR_db_name
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_name
          - name: db_host
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: db_host
      restartPolicy: Never