apiVersion: batch/v1
kind: Job
metadata:
  name: db-drop
  namespace: ${K8S_NAMESPACE}
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: db-drop
        image: ${CI_REGISTRY_IMAGE}:db_drop.${OWN_TAG}
        command: ["python",  "db_drop_tables.py"]
        envFrom:
          - configMapRef:
              name: app-configmap
          - secretRef:
              name: app-secret
      restartPolicy: Never