apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-front
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-front
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-front
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-front
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70