FROM python:3.9-alpine
WORKDIR /app
COPY db_drop_tables.py .
COPY requirements.txt .
RUN pip install psycopg2-binary && pip3 install -r requirements.txt
ENTRYPOINT [ "python" ]
CMD [ "db_drop_tables.py" ]