FROM python:3.9-slim
WORKDIR /app
COPY db_create_tables.py .
COPY requirements.txt .
RUN pip install psycopg2-binary && pip3 install -r requirements.txt
ENTRYPOINT [ "python" ]
CMD [ "db_create_tables.py" ]